name: Work
on: push
jobs:
    build_infra_dev:
        name: Update
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: 'Set up user 🩸'
              uses: fregante/setup-git-user@v1
            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                token: '${{ secrets.LES_ARTICLES }}'
            - run: |
                docker pull capsulecode/singlefile 
                docker tag capsulecode/singlefile singlefile
                docker run singlefile "https://www.wikipedia.org" > wikipedia.html

            - name: Add and commit changes
              run: |
                git add .
                git commit -m "Update"
                git push origin main